//! PureScript code generator

use crate::analyzer::map_type;
use crate::types::{TypeDefinition, TypeKind};

/// Generate PureScript type definition from a Rust type
///
/// This function creates the PureScript type declaration for a given Rust type.
/// Structs are generated as newtypes (for type class instances), and enums are
/// generated as algebraic data types (ADTs).
///
/// # Arguments
///
/// * `type_def` - The Rust type definition to convert to PureScript
///
/// # Returns
///
/// Returns a String containing the PureScript type definition with source comments
///
/// # Examples
///
/// For a Rust struct:
/// ```rust,ignore
/// #[mercury]
/// pub struct User {
///     pub id: i32,
///     pub name: String,
/// }
/// ```
///
/// Generates:
/// ```purescript,ignore
/// newtype User = User
///   { id :: Int
///   , name :: String
///   }
/// ```
pub fn generate_type(type_def: &TypeDefinition) -> String {
    let mut output = String::new();

    // Add comment with source file
    output.push_str(&format!("-- Type: {}\n", type_def.name));
    output.push_str(&format!("-- Source: {}\n", type_def.source_file.display()));
    output.push('\n');

    match &type_def.kind {
        TypeKind::Struct(struct_type) => {
            // Generate newtype for struct (allows type class instances)
            output.push_str(&format!("newtype {} = {} \n", type_def.name, type_def.name));
            output.push_str("  { ");

            for (i, field) in struct_type.fields.iter().enumerate() {
                if i > 0 {
                    output.push_str("\n  , ");
                }

                let ps_type = map_type(&field.field_type);
                output.push_str(&format!("{} :: {}", field.json_name, ps_type));
            }

            output.push_str("\n  }\n");
        }
        TypeKind::Enum(enum_type) => {
            // Generate ADT for enum
            output.push_str(&format!("data {}", type_def.name));

            if !enum_type.variants.is_empty() {
                output.push_str("\n  = ");

                for (i, variant) in enum_type.variants.iter().enumerate() {
                    if i > 0 {
                        output.push_str("\n  | ");
                    }
                    output.push_str(&variant.rust_name);
                }
            }

            output.push('\n');
            output.push('\n');

            // Generate common type class instances for enums
            output.push_str(&format!(
                "derive instance eq{} :: Eq {}\n",
                type_def.name, type_def.name
            ));
            output.push_str(&format!(
                "derive instance ord{} :: Ord {}\n",
                type_def.name, type_def.name
            ));
        }
    }

    output
}

/// Analyze what imports are needed for a module
struct ImportNeeds {
    has_required_fields: bool,
    has_optional_fields: bool,
    has_enums: bool,
}

fn analyze_import_needs(type_defs: &[TypeDefinition]) -> ImportNeeds {
    use crate::types::RustType;

    let mut needs = ImportNeeds {
        has_required_fields: false,
        has_optional_fields: false,
        has_enums: false,
    };

    for type_def in type_defs {
        match &type_def.kind {
            TypeKind::Struct(struct_type) => {
                for field in &struct_type.fields {
                    match &field.field_type {
                        RustType::Option(_) => needs.has_optional_fields = true,
                        _ => needs.has_required_fields = true,
                    }
                }
            }
            TypeKind::Enum(_) => {
                needs.has_enums = true;
            }
        }
    }

    needs
}

/// Generate a complete PureScript module with types and codecs
///
/// Creates a full PureScript module including header comments, imports,
/// type definitions, and Argonaut JSON codecs. Automatically computes
/// cross-module imports for type dependencies.
///
/// # Arguments
///
/// * `module_name` - The PureScript module name (e.g., "Generated.Models")
/// * `type_defs` - The list of type definitions to include in this module
/// * `type_to_module` - Map from type names to their defining modules (for imports)
///
/// # Returns
///
/// Returns a String containing a complete, valid PureScript module
///
/// # Examples
///
/// ```rust,ignore
/// let module = generate_module(
///     "Generated.Models",
///     &[user_type, product_type],
///     &type_map
/// );
/// // Produces a module with header, imports, types, and codecs
/// ```
pub fn generate_module(
    module_name: &str,
    type_defs: &[TypeDefinition],
    type_to_module: &std::collections::HashMap<String, String>,
) -> String {
    let mut output = String::new();

    // Module header
    output.push_str("-- This file was generated by mercury - DO NOT EDIT BY HAND\n");
    output.push_str("-- To regenerate: cargo mercury generate\n");
    output.push('\n');
    output.push_str(&format!("module {} where\n", module_name));
    output.push('\n');

    // Analyze what imports are needed
    let needs = analyze_import_needs(type_defs);

    // Standard imports
    output.push_str("import Prelude\n");
    output.push('\n');

    // Conditional imports based on what's actually used
    let mut decode_imports = vec!["decodeJson"];
    if needs.has_required_fields {
        decode_imports.push("(.:)");
    }
    if needs.has_optional_fields {
        decode_imports.push("(.:?)");
    }
    if needs.has_enums {
        decode_imports.push("JsonDecodeError(..)");
    }
    output.push_str(&format!(
        "import Data.Argonaut.Decode ({})\n",
        decode_imports.join(", ")
    ));

    output.push_str("import Data.Argonaut.Decode.Class (class DecodeJson)\n");
    output.push_str("import Data.Argonaut.Encode.Class (class EncodeJson, encodeJson)\n");

    if needs.has_enums {
        output.push_str("import Data.Either (Either(..))\n");
    }
    if needs.has_optional_fields {
        output.push_str("import Data.Maybe (Maybe(..))\n");
    }

    // Cross-module imports
    let imports = compute_imports(module_name, type_defs, type_to_module);
    if !imports.is_empty() {
        for (import_module, import_types) in imports {
            let types_list = import_types.join(", ");
            output.push_str(&format!("import {} ({})\n", import_module, types_list));
        }
    }

    output.push('\n');

    // Generate each type with its codecs
    for type_def in type_defs {
        output.push_str(&generate_type(type_def));
        output.push('\n');
        output.push_str(&crate::codec_gen::generate_codecs(type_def));
        output.push('\n');
    }

    output
}

/// Compute cross-module imports needed for this module
fn compute_imports(
    current_module: &str,
    type_defs: &[TypeDefinition],
    type_to_module: &std::collections::HashMap<String, String>,
) -> std::collections::BTreeMap<String, Vec<String>> {
    use std::collections::{BTreeMap, BTreeSet};

    let mut imports: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

    // Get all type names defined in this module
    let local_types: BTreeSet<String> = type_defs.iter().map(|t| t.name.clone()).collect();

    // Collect all dependencies from types in this module
    for type_def in type_defs {
        let deps = type_def.collect_dependencies();

        for dep_type in deps {
            // Skip if the type is defined in this module
            if local_types.contains(&dep_type) {
                continue;
            }

            // Look up which module defines this type
            if let Some(dep_module) = type_to_module.get(&dep_type) {
                // Only add import if it's from a different module
                if dep_module != current_module {
                    imports
                        .entry(dep_module.clone())
                        .or_default()
                        .insert(dep_type);
                }
            }
        }
    }

    // Convert BTreeSet to Vec for easier formatting
    imports
        .into_iter()
        .map(|(module, types)| (module, types.into_iter().collect()))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::serde_attrs::SerdeAttrs;
    use crate::types::{Field, RustType, StructType};
    use std::path::PathBuf;

    #[test]
    fn test_generate_simple_struct() {
        let type_def = TypeDefinition {
            name: "User".to_string(),
            source_file: PathBuf::from("test.rs"),
            line: 0,
            kind: TypeKind::Struct(StructType {
                fields: vec![
                    Field {
                        rust_name: "id".to_string(),
                        json_name: "id".to_string(),
                        field_type: RustType::Int,
                    },
                    Field {
                        rust_name: "name".to_string(),
                        json_name: "name".to_string(),
                        field_type: RustType::String,
                    },
                ],
                rename_all: None,
            }),
            serde_attrs: SerdeAttrs::default(),
        };

        let output = generate_type(&type_def);

        assert!(output.contains("newtype User = User"));
        assert!(output.contains("id :: Int"));
        assert!(output.contains("name :: String"));
    }

    #[test]
    fn test_generate_enum_with_derive_instances() {
        use crate::types::EnumVariant;

        let type_def = TypeDefinition {
            name: "Status".to_string(),
            source_file: PathBuf::from("test.rs"),
            line: 0,
            kind: TypeKind::Enum(crate::types::EnumType {
                variants: vec![
                    EnumVariant {
                        rust_name: "Active".to_string(),
                        json_name: "active".to_string(),
                    },
                    EnumVariant {
                        rust_name: "Inactive".to_string(),
                        json_name: "inactive".to_string(),
                    },
                ],
                rename_all: None,
            }),
            serde_attrs: SerdeAttrs::default(),
        };

        let output = generate_type(&type_def);

        // Check enum declaration
        assert!(output.contains("data Status"));
        assert!(output.contains("= Active"));
        assert!(output.contains("| Inactive"));

        // Check derive instances are generated
        assert!(output.contains("derive instance eqStatus :: Eq Status"));
        assert!(output.contains("derive instance ordStatus :: Ord Status"));
    }

    #[test]
    fn test_compute_imports_no_dependencies() {
        use std::collections::HashMap;

        let type_defs = vec![TypeDefinition {
            name: "User".to_string(),
            source_file: PathBuf::from("test.rs"),
            line: 0,
            kind: TypeKind::Struct(StructType {
                fields: vec![Field {
                    rust_name: "id".to_string(),
                    json_name: "id".to_string(),
                    field_type: RustType::Int,
                }],
                rename_all: None,
            }),
            serde_attrs: SerdeAttrs::default(),
        }];

        let type_to_module = HashMap::new();
        let imports = compute_imports("Generated.Test", &type_defs, &type_to_module);

        assert!(
            imports.is_empty(),
            "Should have no imports for primitive types"
        );
    }

    #[test]
    fn test_compute_imports_same_module() {
        use std::collections::HashMap;

        // Two types in the same module, one references the other
        let type_defs = vec![
            TypeDefinition {
                name: "Role".to_string(),
                source_file: PathBuf::from("test.rs"),
                line: 0,
                kind: TypeKind::Enum(crate::types::EnumType {
                    variants: vec![],
                    rename_all: None,
                }),
                serde_attrs: SerdeAttrs::default(),
            },
            TypeDefinition {
                name: "User".to_string(),
                source_file: PathBuf::from("test.rs"),
                line: 0,
                kind: TypeKind::Struct(StructType {
                    fields: vec![Field {
                        rust_name: "role".to_string(),
                        json_name: "role".to_string(),
                        field_type: RustType::Custom("Role".to_string()),
                    }],
                    rename_all: None,
                }),
                serde_attrs: SerdeAttrs::default(),
            },
        ];

        let mut type_to_module = HashMap::new();
        type_to_module.insert("Role".to_string(), "Generated.Test".to_string());
        type_to_module.insert("User".to_string(), "Generated.Test".to_string());

        let imports = compute_imports("Generated.Test", &type_defs, &type_to_module);

        assert!(
            imports.is_empty(),
            "Should have no imports when types are in same module"
        );
    }

    #[test]
    fn test_compute_imports_cross_module() {
        use std::collections::HashMap;

        let type_defs = vec![TypeDefinition {
            name: "User".to_string(),
            source_file: PathBuf::from("test.rs"),
            line: 0,
            kind: TypeKind::Struct(StructType {
                fields: vec![Field {
                    rust_name: "role".to_string(),
                    json_name: "role".to_string(),
                    field_type: RustType::Custom("Role".to_string()),
                }],
                rename_all: None,
            }),
            serde_attrs: SerdeAttrs::default(),
        }];

        let mut type_to_module = HashMap::new();
        type_to_module.insert("Role".to_string(), "Generated.Auth".to_string());
        type_to_module.insert("User".to_string(), "Generated.Models".to_string());

        let imports = compute_imports("Generated.Models", &type_defs, &type_to_module);

        assert_eq!(imports.len(), 1, "Should have one import");
        assert!(imports.contains_key("Generated.Auth"));
        assert_eq!(imports["Generated.Auth"], vec!["Role"]);
    }

    #[test]
    fn test_compute_imports_nested_types() {
        use std::collections::HashMap;

        let type_defs = vec![TypeDefinition {
            name: "UserList".to_string(),
            source_file: PathBuf::from("test.rs"),
            line: 0,
            kind: TypeKind::Struct(StructType {
                fields: vec![
                    Field {
                        rust_name: "users".to_string(),
                        json_name: "users".to_string(),
                        field_type: RustType::Vec(Box::new(RustType::Custom("User".to_string()))),
                    },
                    Field {
                        rust_name: "admin".to_string(),
                        json_name: "admin".to_string(),
                        field_type: RustType::Option(Box::new(RustType::Custom(
                            "Admin".to_string(),
                        ))),
                    },
                ],
                rename_all: None,
            }),
            serde_attrs: SerdeAttrs::default(),
        }];

        let mut type_to_module = HashMap::new();
        type_to_module.insert("User".to_string(), "Generated.User".to_string());
        type_to_module.insert("Admin".to_string(), "Generated.Admin".to_string());
        type_to_module.insert("UserList".to_string(), "Generated.Models".to_string());

        let imports = compute_imports("Generated.Models", &type_defs, &type_to_module);

        assert_eq!(imports.len(), 2, "Should import from two modules");
        assert!(imports.contains_key("Generated.Admin"));
        assert!(imports.contains_key("Generated.User"));
        assert_eq!(imports["Generated.Admin"], vec!["Admin"]);
        assert_eq!(imports["Generated.User"], vec!["User"]);
    }

    #[test]
    fn test_compute_imports_multiple_types_from_same_module() {
        use std::collections::HashMap;

        let type_defs = vec![TypeDefinition {
            name: "UserInfo".to_string(),
            source_file: PathBuf::from("test.rs"),
            line: 0,
            kind: TypeKind::Struct(StructType {
                fields: vec![
                    Field {
                        rust_name: "role".to_string(),
                        json_name: "role".to_string(),
                        field_type: RustType::Custom("Role".to_string()),
                    },
                    Field {
                        rust_name: "status".to_string(),
                        json_name: "status".to_string(),
                        field_type: RustType::Custom("Status".to_string()),
                    },
                ],
                rename_all: None,
            }),
            serde_attrs: SerdeAttrs::default(),
        }];

        let mut type_to_module = HashMap::new();
        type_to_module.insert("Role".to_string(), "Generated.Auth".to_string());
        type_to_module.insert("Status".to_string(), "Generated.Auth".to_string());
        type_to_module.insert("UserInfo".to_string(), "Generated.Models".to_string());

        let imports = compute_imports("Generated.Models", &type_defs, &type_to_module);

        assert_eq!(
            imports.len(),
            1,
            "Should consolidate imports from same module"
        );
        assert!(imports.contains_key("Generated.Auth"));
        let auth_imports = &imports["Generated.Auth"];
        assert_eq!(auth_imports.len(), 2);
        assert!(auth_imports.contains(&"Role".to_string()));
        assert!(auth_imports.contains(&"Status".to_string()));
    }

    #[test]
    fn test_generate_module_with_imports() {
        use std::collections::HashMap;

        let type_defs = vec![TypeDefinition {
            name: "User".to_string(),
            source_file: PathBuf::from("test.rs"),
            line: 0,
            kind: TypeKind::Struct(StructType {
                fields: vec![Field {
                    rust_name: "role".to_string(),
                    json_name: "role".to_string(),
                    field_type: RustType::Custom("Role".to_string()),
                }],
                rename_all: None,
            }),
            serde_attrs: SerdeAttrs::default(),
        }];

        let mut type_to_module = HashMap::new();
        type_to_module.insert("Role".to_string(), "Generated.Auth".to_string());

        let output = generate_module("Generated.Models", &type_defs, &type_to_module);

        assert!(output.contains("module Generated.Models where"));
        assert!(output.contains("import Generated.Auth (Role)"));
        assert!(output.contains("newtype User = User"));
        assert!(output.contains("role :: Role"));
    }
}
